### ISSUE TITLE
Path for class files

### ISSUE THREAD

**Issue by tomvand** [AlexKolpa/AINegotiator#2]
The .class files are currently put in bin/agent/, but the negotiation tool will only recognize them when they are put in agent/. Can we fix this easily or should we copy them by hand?

**Comment by alexwalterbos** [comment]
Quick lookaround: In the `.classpath` file in the root folder, there is an entry called `output` which, I guess, specifies the output directory. This is set to `bin`. So when output is generated for a folder `/agent/`, it would be put under `bin/agent/`. I am currently not yet working with the code, but I think setting that output value in `.classpath` to `/` (via the IDE settings, I don't know how much Eclipse etc will like you messing around with the raw files) should fix this.

**Comment by tomvand** [comment]
Tried it, both methods cause an error in eclipse. Apparently output must be inside a subfolder.

**Comment by alexwalterbos** [comment]
I've looked around but can't find it yet: Is there any option we can tell the Negotiator app to scan other folders for agents?

**Comment by tomvand** [comment]
If the option exists, I haven't found it. By default you can add classes if they are in the correct folder as defined by their package. For instance, Group1_AS.class should be put in agent/, otherwise adding it to the BOA components produces an error.

**Comment by alexwalterbos** [comment]
@tomvand, this was solved, or not yet?

**Comment by tomvand** [comment]
No, I did not look further into this. For now, the classes have to be copied to `negotiator/group1/` manually.

**Comment by alexwalterbos** [comment]
Hmm.. sucks. I'll look into this further. Is it perhaps an idea to ask another group how they manage this?

**Comment by tomvand** [comment]
Yes, that would be helpful, although I don't think this is a priority at the moment.

**Comment by alexwalterbos** [comment]
That's true.
